# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
# Serena MCP Integration
serena:
  default_mode: "editing"
  memory_persistence: true
  pure_integration: true

# Serena-optimized startup symbols (replaces devLoadAlwaysFiles)
devSerenaStartup:
  - symbol: "docs/architecture/coding-standards.md#main-patterns"
  - symbol: "docs/architecture/tech-stack.md#current-stack"
  - symbol: "docs/architecture/source-tree.md#structure-overview"

# Workflow orchestration configuration
workflow_tracking:
  enabled: true
  auto_navigate: true
  progress_memory: true
  transition_prompts: true
  state_detection: true
  completion_guidance: true

devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
